# coding=utf-8

members_zh = {'allen.han': '韩超',
              'victor.yuan': '袁国勇',
              'mike.wang': '王军锋',
              'jack.wang': '王冰星',
              'karl.zhu': '朱海',
              'george.jiang': '蒋义明',
              'jordan.jing': '井文',
              'tina.zhang': '张海霞',
              'derek.zhang': '张蔚萍',
              'wayne.zhao': '赵玉勇',
              'wendy.zhang': '张彧',
              'will.lee': '李洁',
              'tom.peng': '彭凯',
              'guojia': '郭佳',
              'lixing': '李星',
              'lihu': '李虎',
              'xiejiafu': '谢家富',
              'zhangzhengwu': '张正武',
              'fan.wang': '王凡',
              'david.xu': '徐若愚',
              'pip.zhang': '张朝勇',
              'eben.xie': '谢钢',
              'robin.ni': '倪旭春',
              'will.zhang': '张保',
              'wade.wei': '魏巍',
              }
